version: '3.8'

services:

  workerapp:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    ports:
      - '5000:80'
    depends_on:
      - "db"

  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=administrativedb
      - MYSQL_ROOT_PASSWORD=RooT146@1
    ports:
      - '3306:3306'

volumes:
  mysql-data: